root = "backend"

[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && chmod +x node_modules/.bin/tsc && npm run build"

[variables]
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "npm run start"
