name: compostos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # App dependencies
  go_router: ^16.2.4
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  dio: ^5.8.0
  http: ^1.2.1
  intl: ^0.20.2
  share_plus: ^12.0.0
  timezone: ^0.9.4
  syncfusion_flutter_charts: ^31.1.19
  mask_text_input_formatter: ^2.5.0
  provider: ^6.1.2
  web_socket_channel: ^3.0.1

dev-dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
