project_id = "misswwtaysshbnnsjhtv"

[functions.send-signup-confirmation]
verify_jwt = false

[auth]
enabled = true
site_url = "https://comituga.eu"
additional_redirect_urls = [
  "https://comituga.eu/**", 
  "http://localhost:8080", 
  "http://localhost:5173/**",
  "saborportugues://login",
  "saborportugues://*"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
# sso_refresh_token_reuse_interval = 600
# session_idle_timeout = 600
# external_url = ""

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 7200  # 2 horas em vez de 1 hora

[auth.email.template]
# Template será configurado no dashboard web depois