name: Deploy Vercel (menu-online.site)

on:
  push:
    branches: [ main ]
    paths:
      - 'Menu-digital/**'

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ secrets.VERCEL_TOKEN != '' }}
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Environment
        working-directory: Menu-digital
        run: vercel pull --yes --environment=production --token "$VERCEL_TOKEN"

      - name: Build (optional, prebuilt)
        working-directory: Menu-digital
        run: vercel build --prod --token "$VERCEL_TOKEN"

      - name: Deploy to Production
        working-directory: Menu-digital
        run: vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"
